name: Update MX

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (you can adjust this)
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('MX/*.py') }}  # Cache key based on OS and Python scripts
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: pip install requests pandas

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.x'

      # - name: Cache R package dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.R/  # Location where R packages are installed
      #     key: ${{ runner.os }}-R-${{ hashFiles('MX/*.R') }}  # Unique cache key based on OS and R scripts
      #     restore-keys: |
      #       ${{ runner.os }}-R-

      # - name: Install R dependencies
      #   run: |
      #     Rscript -e 'if (!requireNamespace("tidyverse", quietly = TRUE)) install.packages(c("httr", "jsonlite", "lubridate", "tidyverse"))'

      - name: Run all Python scripts in MX folder
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          BANXICO_API_KEY: ${{ secrets.BANXICO_API_KEY }}
          INEGI_API_KEY: ${{ secrets.INEGI_API_KEY }}
        run: |
          for script in MX/*.py; do
            python "$script"
          done

      # - name: Run all R scripts in MX folder
      #   run: |
      #     for script in MX/*.R; do
      #       Rscript "$script"
      #     done

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add 'MX/*.csv'  # Add all CSV files from the specific folder
          git commit -m "Update data" || echo "No changes to commit"
          git push
