name: Update MX

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (you can adjust this)
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests pandas camelot-py

      - name: Run all Python scripts in MX folder
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          BANXICO_API_KEY: ${{ secrets.BANXICO_API_KEY }}
          INEGI_API_KEY: ${{ secrets.INEGI_API_KEY }}
        run: |
          for script in MX/*.py; do
            python "$script"
          done

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add 'MX/*.csv'  # Add all CSV files from the specific folder
          git commit -m "Update data" || echo "No changes to commit"
          git push
